### ISSUE TITLE
TXSTART metadata ignores strand directionality?

### ISSUE THREAD

**Issue by JakeLehle** [Bioconductor/OrganismDbi#2]
Hello,

Love the package. Saw an issue I want to discuss.

Okay so I was using the Mus.Musculus AnnotateDbi database package to make a genomic ranges object containing all of the promoters and because I have access to your wonderful package through the AnnotateDbi framework I can now slap all that wonderful metdata on to this object in one go instead of having to merge 3 different databases together via ENTRZID.

Here was the code I ran.

```
# Package setup
BiocManager::install("OrganismDbi")
library(OrganismDbi)
BiocManager::install("Mus.musculus")
library(Mus.musculus)
BiocManager::install("GenomicFeatures")
library(GenomicFeatures)

# Making this object just for comparison
Mm_gene <- transcriptsBy(Mus.musculus, by="gene", columns=c("SYMBOL", "ENTREZID", "TXCHROM",  "TXSTART", "TXSTRAND", "CDSSTART"))
Mm_gene

# Here is the promoter object. You can see I'm calling 1500 bp upstream of the transcription start and 500 bp downstream of the transcription start site my "promoter region" for this analysis.
Mm_gene_promoters <- promoters(transcriptsBy(Mus.musculus, by="gene", columns=c("SYMBOL", "ENTREZID", "TXCHROM",  "TXSTART", "TXSTRAND", "CDSSTART")), upstream = 1500, downstream = 500)
Mm_gene_promoters
```

Below are screenshots of the outputs.
Mm_gene
![image](https://user-images.githubusercontent.com/84940857/205757744-bed21df5-6e35-4cd2-8f64-44ffa64ab3ad.png)

Even though the transcripts are on the minus strand the database is calling that start of the transcript as the first base pair from the genomic range object.

![image](https://user-images.githubusercontent.com/84940857/205757099-d37dfc81-6376-45dc-bb89-326208555e16.png)

Here you can see that the promoters() function from genomicFeatures gets it right and assigns my promoter region as 1500 bases upstream and 500 downstream to the transcription start site for _Zglp1_ which is coming from the minus strand and should be adding 1500 bp to the last bp of the genomic ranges and then subtracting 500 bp to get the correct ranges.

This is something I saw and was curious if the TXSTART metadata coming from the Mus.Musculus package was just being scraped from the first base pair of the genomic ranges. This would be super simple to add in an "if loop" and have it grab the last base pair in the ranges instead for transcripts on the minus strand. Otherwise this is going to lead to some confusion from people trying to use this metadata and not knowing where these numbers are coming from.

**Comment by hpages** [comment]
Hi @JakeLehle 

Yes TXSTART refers to the position of the first (i.e. left-most) nucleotide of the transcript, and TXEND to the last (i.e. right-most) position of the transcript, regardless of the strand. This is consistent with the terminology used for describing genomic intervals in Bioconductor, and with the names of the `start()` and `end()` accessors that can be used on all range-based objects in Bioconductor e.g. on IRanges, IRangesList, GRanges, GRangesList, etc... objects.

For example:
```
> library(TxDb.Mmusculus.UCSC.mm10.knownGene)
> txdb <- TxDb.Mmusculus.UCSC.mm10.knownGene
> tx_ranges <- transcripts(txdb)
> tx_ranges
GRanges object with 142446 ranges and 2 metadata columns:
                 seqnames          ranges strand |     tx_id
                    <Rle>       <IRanges>  <Rle> | <integer>
       [1]           chr1 3073253-3074322      + |         1
       [2]           chr1 3102016-3102125      + |         2
       [3]           chr1 3252757-3253236      + |         3
       [4]           chr1 3466587-3513553      + |         4
       [5]           chr1 3531795-3532720      + |         5
       ...            ...             ...    ... .       ...
  [142442] chrUn_GL456381     16623-16721      - |    142442
  [142443] chrUn_GL456385     31243-31343      + |    142443
  [142444] chrUn_GL456385     32719-32818      + |    142444
  [142445] chrUn_JH584304     52190-59667      - |    142445
  [142446] chrUn_JH584304     52691-59690      - |    142446
                        tx_name
                    <character>
       [1] ENSMUST00000193812.1
       [2] ENSMUST00000082908.1
       [3] ENSMUST00000192857.1
       [4] ENSMUST00000161581.1
       [5] ENSMUST00000192183.1
       ...                  ...
  [142442] ENSMUST00000184505.1
  [142443] ENSMUST00000178705.1
  [142444] ENSMUST00000180206.1
  [142445] ENSMUST00000179505.7
  [142446] ENSMUST00000178343.1
  -------
  seqinfo: 66 sequences (1 circular) from mm10 genome

> head(start(tx_ranges))
[1] 3073253 3102016 3252757 3466587 3531795 3680155

> head(end(tx_ranges))
[1] 3074322 3102125 3253236 3513553 3532720 3681788

> ranges(tx_ranges)
IRanges object with 142446 ranges and 0 metadata columns:
               start       end     width
           <integer> <integer> <integer>
       [1]   3073253   3074322      1070
       [2]   3102016   3102125       110
       [3]   3252757   3253236       480
       [4]   3466587   3513553     46967
       [5]   3531795   3532720       926
       ...       ...       ...       ...
  [142442]     16623     16721        99
  [142443]     31243     31343       101
  [142444]     32719     32818       100
  [142445]     52190     59667      7478
  [142446]     52691     59690      7000

> ex_ranges <- exons(txdb)
> ex_ranges
GRanges object with 447558 ranges and 1 metadata column:
                 seqnames          ranges strand |   exon_id
                    <Rle>       <IRanges>  <Rle> | <integer>
       [1]           chr1 3073253-3074322      + |         1
       [2]           chr1 3102016-3102125      + |         2
       [3]           chr1 3252757-3253236      + |         3
       [4]           chr1 3466587-3466687      + |         4
       [5]           chr1 3513405-3513553      + |         5
       ...            ...             ...    ... .       ...
  [447554] chrUn_JH584304     55112-55701      - |    447554
  [447555] chrUn_JH584304     56986-57151      - |    447555
  [447556] chrUn_JH584304     58564-58835      - |    447556
  [447557] chrUn_JH584304     58564-59690      - |    447557
  [447558] chrUn_JH584304     59592-59667      - |    447558
  -------
  seqinfo: 66 sequences (1 circular) from mm10 genome

> ranges(ex_ranges)
IRanges object with 447558 ranges and 0 metadata columns:
               start       end     width
           <integer> <integer> <integer>
       [1]   3073253   3074322      1070
       [2]   3102016   3102125       110
       [3]   3252757   3253236       480
       [4]   3466587   3466687       101
       [5]   3513405   3513553       149
       ...       ...       ...       ...
  [447554]     55112     55701       590
  [447555]     56986     57151       166
  [447556]     58564     58835       272
  [447557]     58564     59690      1127
  [447558]     59592     59667        76
```
Note that we use the same convention for all intervals, whatever genomic features they are associated with (e.g. transcripts, exons, genes, CDS, etc...) and whatever the strand.

So in your case TXSTART is just that, the start of the transcripts. It has nothing to do with the TSS (transcription start sites). Of course `promoters()` needs to do the right thing which is to compute the promoter regions with respect to the TSS. And it looks like that's what it's doing here.

If you want to add the TSS to the _inner_ metadata columns of GRangesList objects `Mm_gene` and `Mm_gene_promoters`, you can do:
```
library(Mus.musculus)

Mm_gene <- transcriptsBy(Mus.musculus, by="gene", columns=c("SYMBOL", "ENTREZID"))

## Unlist, modify, relist (this is a common trick to operate efficiently on List derivatives):
unlisted_Mm_gene <- unlist(Mm_gene, use.names=FALSE)
TSS <- ifelse(strand(unlisted_Mm_gene) == "+", start(unlisted_Mm_gene), end(unlisted_Mm_gene))
mcols(unlisted_Mm_gene)$TSS <- TSS
Mm_gene <- relist(unlisted_Mm_gene, Mm_gene)

Mm_gene_promoters <- promoters(Mm_gene, upstream=1500, downstream=500)

Mm_gene_promoters
# GRangesList object of length 24594:
# $`100009600`
# GRanges object with 2 ranges and 4 metadata columns:
#       seqnames            ranges strand |              tx_name          SYMBOL
#          <Rle>         <IRanges>  <Rle> |          <character> <CharacterList>
#   [1]     chr9 21066594-21068593      - | ENSMUST00000115494.2           Zglp1
#   [2]     chr9 21072597-21074596      - | ENSMUST00000213826.1           Zglp1
#              ENTREZID       TSS
#       <CharacterList> <integer>
#   [1]       100009600  21067093
#   [2]       100009600  21073096
#   -------
#   seqinfo: 66 sequences (1 circular) from mm10 genome
# 
# $`100009609`
# GRanges object with 4 ranges and 4 metadata columns:
#       seqnames            ranges strand |              tx_name          SYMBOL
#          <Rle>         <IRanges>  <Rle> |          <character> <CharacterList>
#   [1]     chr7 84963616-84965615      - | ENSMUST00000044583.9         Vmn2r65
#   [2]     chr7 84963616-84965615      - | ENSMUST00000232823.1         Vmn2r65
#   [3]     chr7 84963616-84965615      - | ENSMUST00000233024.1         Vmn2r65
#   [4]     chr7 84963616-84965615      - | ENSMUST00000233469.1         Vmn2r65
#              ENTREZID       TSS
#       <CharacterList> <integer>
#   [1]       100009609  84964115
#   [2]       100009609  84964115
#   [3]       100009609  84964115
#   [4]       100009609  84964115
#   -------
#   seqinfo: 66 sequences (1 circular) from mm10 genome
# 
# $`100009614`
# GRanges object with 1 range and 4 metadata columns:
#       seqnames            ranges strand |              tx_name          SYMBOL
#          <Rle>         <IRanges>  <Rle> |          <character> <CharacterList>
#   [1]    chr10 77709957-77711956      + | ENSMUST00000075421.6         Gm10024
#              ENTREZID       TSS
#       <CharacterList> <integer>
#   [1]       100009614  77711457
#   -------
#   seqinfo: 66 sequences (1 circular) from mm10 genome
# 
# ...
# <24591 more elements>
```
Unfortunately this is not a built-in feature.

Hope this helps.

H.

**Comment by JakeLehle** [comment]
Hi @hpages,

Thank you for getting back to me with this detailed response I will absolutely incorporate that ifelse loop into my own scripts to add on the TSS to my promoters dataset it now makes total sense to pull that together that way. 

Thank you for also clarifying the distinction between the start of a transcript, indicated by the TXSTART metadata, and the transcription start site that I was looking for in the possible preexisting metadata columns. Since many transcripts have CDS data indicated I made the quick assumption that the TSS would also be listed. But it makes sense you could quickly derive it with many of the tools available and a good understanding of the core functions like start(), end(), of the genomic ranges family of package library. Hopefully, this thread will help others who could get confused with this smaller detail in the future as well.

I'll close this issue out with this comment.

P.S.

Are there any other review articles or resources that you could point me to that have a more generalized idea of current best practices or active areas of development by Bioconductor? For examples: like the most common different families of packages used under the Bioconductor umbrella and generalized questions that these packages are usually applied to or available databases that everyone should have a good handle on like TxDb, Org, BioMart, etc? Playing around with those three databases individually is actually what led me to find this package when I was trying to string those databases together using ENTRESZIDs and felt like I was trying to reinvent the wheel and this must already exist somewhere and boom you guys already have it set up and ready to use.
I feel like I'm constantly reading and trying to play catchup with packages like OrganismDbi and the AnnotateDbi framework that combine multiple preexisting databases together to overcome a ton of the issues and legwork many people were doing in the past individually to quickly annotate transcripts but I wish there was a historical record to point so I wasn't waiting my time building something already existing.

**Comment by hpages** [comment]
James MacDonald (@jmacdon) frequently gives a workshop named "Introduction to Bioconductor annotation resources" at the Bioconductor annual conference, and maybe at other venues. See for example: https://bioc2022.bioconductor.org/workshops/ . Note that the material of the workshop (source code + video) is available.

The exact name of the workshop might slightly vary from one year to the other.

This workshop is a classic. It will teach you how to navigate the huge amount of annotations available in Bioconductor. Anybody who is new to Bioconductor should take it. I don't know if it covers the so called "OrganismDb packages" though (e.g.  **Homo.sapiens**, **Mus.musculus**, etc...)

Don't hesitate to ask on our [support site](https://support.bioconductor.org) or on the community-bioc Slack (link to the Slack sign-up is on our website [here](https://bioconductor.org/)) if you need more recommendations.

Best,
H.

**Comment by jmacdon** [comment]
@JakeLehle, @hpages The workshop does cover the OrganismDb packages, as well as the Organism.dplyr package, which allows one to create a virtual OrganismDb package for all the organisms for which there aren't any OrganismDb packages. As Herve notes, the support site is a better venue for this sort of discussion.

**Comment by JakeLehle** [comment]
Awesome, I just made an orchestra account and I'll start digging through those workshops. 
I really appreciate you both pointing me toward those resources!

Thanks!
